### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mdiephuis** [mdiephuis/fix-match#1]
# Augmentation
sample param, make choice
- [x]  auto contrast
- [x] brightness
- [x] to grayscale with prob p
- [x] constrast change
- [x] equalize
- [x] invert 
- [x] do nothing
- [x] rescale
- [x] posterize
- [x] solarize
- [x] rotate + rescale
- [x] sharpness
- [x] smooth
- [x] flipx
- [x] flipy

# General
- [x] first training loop
- [x] define losses
- [x] add accuracy
- [ ] add cosine warmup 
- [ ] initialization
